### ISSUE TITLE
Printing large bitmap 4x6"

### ISSUE THREAD

**Issue by digdesk** [karronoli/tiny-sato#4]
The addBitmap or addGraphic does not allow any large images. Can it be done by passing an array of image objects that get printed in a row x  column format?

**Comment by karronoli** [comment]
Thank you for using!
`Graphic.AddBitmap` can accept small image only. (99999byte on 1depth bitmap)
If you print any large image, Use `Graphic.AddGraphic`.
I have printed about width 10cm over & height 20cm over at 203dpi.

Here is a usage sample.
If you desire, you should be able to print even larger sizes.
[UnitTest1.cs](../blob/master/UnitTestProject/UnitTest1.cs#L205-L218)

**Comment by Digvijay** [comment]
Thanks for responding!

I will check and close the issue if that works!

**Comment by digdesk** [comment]
Hi,

I tried but the documents always stay in the printer queue and never print!

**Comment by karronoli** [comment]
Did you check a printer status? online?
If a printer job is added to windows printer queue, your program is OK. SATO printer prints something.
What do you use a printer model?
I use [(maybe) MB400i compatible](http://www.sato.co.jp/products/printer/lapinPT.html) and [(maybe) CT4i compatible](http://www.sato.co.jp/products/printer/lesprit_t408v412v_r408v412v.html)

**Comment by Digvijay** [comment]
Yes, printer is always online.

i believe SAT waits for some commands which i might not be sending

Can you help by sharing a simple console app that prints a 10x20 cm as you mentioned earlier. ANy bitmap will do.

Thanks in advance!

**Comment by karronoli** [comment]
Sure! I'll develop a simple console app.
What does you mean 'SAT'? SATO?? Is it a printer model?

**Comment by Digvijay** [comment]
yes, it was a typo - i meant SATO.

**Comment by karronoli** [comment]
@Digvijay 
Add ExampleConsole Project. You can try [ExampleConsole](../tree/feature/new-connection-ways/ExampleConsole) .
ExampleConsole [printer name] [dpi]
`> ExampleConsole T408v 203`

By the way, What a model do you use the SATO printer?
As you know, You may have to change a SATO printer setting to use SBPL. (by DIP switch, etc.)
Old SATO printer doesn't support SBPL.

Please let me know a your SATO printer model.

**Comment by dhongki** [comment]
Is this still active? is there any documentation on how to use this? thank you :-D

**Comment by karronoli** [comment]
@dhongki 
It's active! I use this library every day. But any documentation is none.
If UnitTestProject/UnitTest1.cs is not enough for you,  I'll write some document.

**Comment by dhongki** [comment]
sorry i am just new this. I am trying to compile  that sample using vs2012 and i am getting errors. Am i doing wrong? :-(

![tiny-sato](https://user-images.githubusercontent.com/28613377/34974530-8465a4ba-fac8-11e7-8e08-a3669cda1f32.png)

**Comment by karronoli** [comment]
@dhongki 
First. Create new issue.
Second. Use Nuget. https://www.nuget.org/packages/TinySato/
